FROM node:18-alpine AS base

# Install pnpm
RUN npm install -g pnpm

# Set working directory
WORKDIR /app

# Copy package files first for better caching
COPY package.json pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install

# Copy the entire project except files in .dockerignore
COPY . .

# Configure Next.js for standalone output
RUN if [ ! -f next.config.js ]; then echo "module.exports = { output: 'standalone' };" > next.config.js; else sed -i '/output/d' next.config.js && sed -i 's/module.exports = {/module.exports = { output: "standalone",/g' next.config.js; fi

# Build the application
RUN pnpm build

# Production image, copy all the files and run next
FROM node:18-alpine AS runner
WORKDIR /app

# Set environment variables
ENV NODE_ENV production
ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

# Copy necessary files from the build stage
COPY --from=base /app/.next/standalone ./
COPY --from=base /app/.next/static ./.next/static
COPY --from=base /app/public ./public

# Expose the port
EXPOSE 3000

# Start the application - use server.js which is generated by Next.js standalone output
CMD ["node", "server.js"] 